### ISSUE TITLE
Add a prefix to the generate PR

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/cloud-hosted-guide-converter#10]
The convertor generates PR to the staging or master branch. Suggest to add a prefix for the PR title as following:

- `To staging: Change to cloud-hosted-guide-cdi-intro`
- `To master: Change to cloud-hosted-guide-cdi-intro`

**Comment by jakub-pomykala** [comment]
https://github.com/OpenLiberty/quick-labs/pull/151

**Comment by jakub-pomykala** [comment]
The PR has now been merged.
