### ISSUE TITLE
Specify the guide name at step 1 

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/cloud-hosted-guide-converter#104]
"Step 1 - Welcome to the cloud-hosted guide!" -- Should be specific and identify the specific guide that users have decided to use

**Comment by jakub-pomykala** [comment]
This is now in place please verify with any of the guides on master.

**Comment by jakub-pomykala** [comment]
@gkwan-ibm @jamiecoleman92 @yeekangc
