### ISSUE TITLE
Feedback for MST guide

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/cloud-hosted-guide-converter#105]
- Step 2
  - [x] missing content between "Learn more..." and "mvn verify"
    - ![Screen Shot 2021-02-12 at 3 00 40 PM](https://user-images.githubusercontent.com/29576299/107816749-34bd7500-6d43-11eb-961f-51c5cc6cac6c.png)
- Step 8 and 9
  -  [ ] both steps should not be separated

**Comment by jakub-pomykala** [comment]
In regards to step 2 this has now been resolved. However the guide converter is not able to conclude which steps are together or not. It converts h1 to h1, h2 to h1 and h3 to h2

**Comment by gkwan-ibm** [comment]
> Step 8 and 9: both steps should not be separated

better to combine
```
== Great work! You're done!
...
== Related Links
...
```
when the convertor reach `Great work! You're done!`, not generate new step for `Related Links`
