### ISSUE TITLE
Feedback for kubernetes-intro guide

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/cloud-hosted-guide-converter#106]
- [ ] step 2 and 3 should not be separated
- [x] there are 12 step, but at step 7 no next arrow at the top and no next button at the bottom

**Comment by jakub-pomykala** [comment]
In regards to step 7 arrow just need to refresh the guide and that will be fixed. Sometimes we just have to give the environment another chance to load

**Comment by gkwan-ibm** [comment]
> step 2 and 3 should not be separated

let do following:
- Move the title and short description at step 2 to the step 1 Welcome step
- "What you’ll learn" at step 3 can be a separated step
