### ISSUE TITLE
Feedback for containerize guide

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/cloud-hosted-guide-converter#107]
- Step 5
  - [x] following was converted incorrectly
    - ![Screen Shot 2021-02-16 at 3 02 17 PM](https://user-images.githubusercontent.com/29576299/108115624-621e6180-7068-11eb-9bae-4eccfcf2955f.png)
  - [ ] `The COPY instructions are structured as COPY [--chown=:] . ` misses the user and group. It should be `[--chown=<user>:<group>]`
- Step 7
  - [x] at the bottom, the following link was converted incorrectly
    - `To learn more about Open Liberty server configuration, check out the [https://openliberty.io/docs/latest/reference/config/server-configuration-overview.htmlServer Configuration Overview] docs. `
- [x] Steps 9 to 11  were converted incorrectly

**Comment by jakub-pomykala** [comment]
@gkwan-ibm can you please verify that this issue is now resolved?

**Comment by gkwan-ibm** [comment]
@jakub-pomykala 
I unchecked
> The COPY instructions are structured as COPY [--chown=:] . misses the user and group. It should be [--chown=<user>:<group>]

**Comment by jakub-pomykala** [comment]
![Screenshot 2021-02-19 at 16 10 25](https://user-images.githubusercontent.com/56261244/108529975-fc7edf00-72cc-11eb-9e94-b6285de69eda.png)
If you have a look at the above screen shot it is in there. This means that there must be a problem with the way SNL renders this.

**Comment by jakub-pomykala** [comment]
@gkwan-ibm

**Comment by gkwan-ibm** [comment]
@jakub-pomykala let see what can do to make the lab to show `<user>:<group>` first, then concern how to achieve it

**Comment by jakub-pomykala** [comment]
Messaged SNL to ask why this is happening.

**Comment by jakub-pomykala** [comment]
This is the same issue as #47 , however instead of `_` being a problem `<` and `>` causes the problem
