### ISSUE TITLE
invalid markdown instructions in staging SN

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/cloud-hosted-guide-converter#11]
Got `invalid markdown instructions` when run the following in staging SN:
- [ ] cloud-hosted-guide-rest-intro
- [ ] cloud-hosted-guide-containerize
- [ ] cloud-hosted-guide-microprofile-config
- [ ] cloud-hosted-guide-microprofile-fallback
- [ ] cloud-hosted-guide-microprofile-rest-client
- [ ] cloud-hosted-getting-started

![Screen Shot 2020-12-11 at 3 22 27 PM](https://user-images.githubusercontent.com/29576299/101951407-f251ad80-3bc4-11eb-8675-7049ad1b7cf7.png)

**Comment by jakub-pomykala** [comment]
Could you please provide the links you are trying to run these guides from?

**Comment by jakub-pomykala** [comment]
Fixed. Issue was where the names of the guides where changed to `cloud-hosted-...` I kicked off the master branches on gitlab but forgot to kick off the staging. After kicking off all the staging branches there should be no more problems like this.
