### ISSUE TITLE
Enable the 3rd set of guides

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/cloud-hosted-guide-converter#110]
- [ ] microprofile-istio-retry-fallback
- [ ] microprofile-jwt
- [ ] microprofile-metrics
- [ ] microprofile-openapi
- [ ] microprofile-reactive-messaging-acknowledgment
- [ ] microprofile-reactive-messaging-rest-integration
- [ ] microprofile-rest-client-async

**Comment by jakub-pomykala** [comment]
All guides are live on Staging @gkwan-ibm

**Comment by jakub-pomykala** [comment]
All Guides apart from microprofile-istio-rety-fallback have the GuideConverter action enabled now
