### ISSUE TITLE
The links at Where to next section should open a new tab

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/cloud-hosted-guide-converter#121]
When user click on the guides links at Where to next section, the links should open a new browser tab.

**Comment by jakub-pomykala** [comment]
After carrying out some research, testing (on the [cloud-hosted-draft-guide-development](https://labs.cognitiveclass.ai/tools/theiadocker/lab/tree?md_instructions_url=https://cf-course-data-staging.s3.us-east.cloud-object-storage.appdomain.cloud/cloud-hosted-draft-guide-development/instructions.md)) and having a conversation with Skills Network Labs teams this is not possible at this moment. Looking at the RAW instructions.md you can see that I have tried doing this in two different ways.

First way is by adding `{:target="_blank"}` to the end of the link. This requires and extension installed to showdown (parser used by SNL). This does indeed work where the link does open in a new tab but the code is also rendered next to the link (as seen in the second screenshot or on the lab (link provided above)).

The last link in this screenshot is implemented using plain HTML. This did indeed render the link correctly but it does not open it in a new tab as expected although `target="_blank"` has been added. After speaking to SNL team we realised that the instructions are rendered/parsed correctly from GitLab to the cloud however after being parsed using ShowDown these are removed.

![Screenshot 2021-03-11 at 10 29 39](https://user-images.githubusercontent.com/56261244/110773681-ebcee280-8254-11eb-8727-4a8ca3c3c339.png)
![Screenshot 2021-03-11 at 10 30 47](https://user-images.githubusercontent.com/56261244/110773688-ed000f80-8254-11eb-8f84-68c73e7c5b12.png)

**Comment by jakub-pomykala** [comment]
This should have now been fixed by Skills Network so all links open in a new tab by default

**Comment by jakub-pomykala** [comment]
Still waiting for an update from Skills Network.

**Comment by tt-le** [comment]
Verified in production, links seem to be all opening in a new browser tab.

**Comment by gkwan-ibm** [comment]
Thank you @tt-le

**Comment by gkwan-ibm** [comment]
close
- the issue was addressed by SN
