### ISSUE TITLE
Manually convert all guides failed 

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/cloud-hosted-guide-converter#124]
manually convert all guides failed - https://github.com/OpenLiberty/cloud-hosted-guides/actions/runs/624902380

**Comment by jakub-pomykala** [comment]
The action failed because in some guides there was nothing to commit. Therefore this failed.

**Comment by jakub-pomykala** [comment]
I have changed the action so even if a guide conversion fails on one or there is nothing to commit on one guide all the others will still run instead of being cancelled.
