### ISSUE TITLE
Containerzie guide step 2 is empty

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/cloud-hosted-guide-converter#126]
can find following in https://raw.githubusercontent.com/OpenLiberty/cloud-hosted-guides/62aa9dfda47b870ae9c03c4f4a0df0c8db391268/instructions/cloud-hosted-guide-containerize/instructions.md

```

# Containerizing microservices


# What you'll learn
```

**Comment by jakub-pomykala** [comment]
Created PR [here](https://github.com/OpenLiberty/guide-containerize/pull/88)

**Comment by jakub-pomykala** [comment]
https://github.com/OpenLiberty/cloud-hosted-guide-converter/pull/127
