### ISSUE TITLE
The getting started cloud-hosted guide only have 1 step

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/cloud-hosted-guide-converter#13]
It is not right only have 1 step.

![Screen Shot 2020-12-14 at 10 10 06 AM](https://user-images.githubusercontent.com/29576299/102097993-9bcab600-3df4-11eb-8b7e-2f4d73e14720.png)

**Comment by jakub-pomykala** [comment]
Issue addressed and fixed.
