### ISSUE TITLE
Consider a manual github action to generate instruction.md from static guide to the cloud-hosted-draft-guide-development

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/cloud-hosted-guide-converter#130]
For development purpose, when I update the static guide, I want to know whether my change is good or not in the SN.
I don't want to commit the change to the qa/staging branch.
I want a way to trigger the conversion and there is a draft/development quicklab for me to verify.

Suggest a manual github action with following information:
- static guide name, e.g. guide-microprofile-opentracing-jaeger
- static guide branch, e.g. gkwan-ibm-patch-1

to generate a PR to update the https://github.com/OpenLiberty/cloud-hosted-guides/blob/staging/instructions/cloud-hosted-draft-guide-development/instructions.md on the staging branch. After merge the PR, the cloud-hosted-draft-guide-development quicklab will be available to verify the change.

**Comment by jakub-pomykala** [comment]
https://github.com/OpenLiberty/cloud-hosted-guides/pull/573

**Comment by jakub-pomykala** [comment]
We can now close this issue as the action has been created and tested.
