### ISSUE TITLE
Issue when converting tables from adoc to md

### ISSUE THREAD

**Issue by AustinSeto** [OpenLiberty/cloud-hosted-guide-converter#139]
`.adoc` files allow cells in tables to be defined across multiple lines. For example, you can do something like:

```
| cell 1 | cell 2 part 1 
cell 2 part 2
```

This does not work in `.md` files to my knowledge, and would result in a broken table.

Issue noticed when working with Microprofile OpenAPI guide

[Input file to converter](https://github.com/OpenLiberty/guide-microprofile-openapi/blob/b5576c29e2479feb27fe37cb737f9d92c1e1dd0b/README.adoc)

[Output file from converter](https://github.com/OpenLiberty/cloud-hosted-guides/blob/ead687d8f2163207c39bdc0541e02fd0152e00a7/instructions/cloud-hosted-guide-microprofile-openapi/instructions.md)

**Comment by jamiecoleman92** [comment]
This issue should be fixed by the Adoc files rather than the converter.
