### ISSUE TITLE
Broken Link in "Providing metrics from a microservice guide"

### ISSUE THREAD

**Issue by rutavshah** [OpenLiberty/cloud-hosted-guide-converter#140]
In the cloud version of [Providing metrics from a microservice guide](https://openliberty.io/guides/microprofile-metrics.html), the link at the end of step 4 is broken. The same link in the [GitHub repository](https://github.com/OpenLiberty/guide-microprofile-metrics) redirects to the correct page.

**Comment by jakub-pomykala** [comment]
Issue was fixed by SNL, myself and @austin0 have verified that this is now fixed.
