### ISSUE TITLE
Wrong code provided to replace file 

### ISSUE THREAD

**Issue by priyyanshi** [OpenLiberty/cloud-hosted-guide-converter#141]
Testing the microprofile-opentracing([PR](https://github.com/OpenLiberty/guide-microprofile-opentracing/pull/139)) guide on dev lab 3, in step 6 the code provided to replace the `InventoryResource` class is for `InventoryManager` class. The lgdev site has the correct code but the cloud-hosted does not.

**Comment by gkwan-ibm** [comment]
microprofile-opentracing-jaeger has the same issue. At step 6/8, the first update InventoryManager content should be different than the 2nd replace of InventoryManager content. 
Need to confirm whether the static guide can fix this problem

**Comment by gkwan-ibm** [comment]
There are 2 issues for the converter:
1. when determine `hide_tags`, the converter only look up 10 lines ahead
  - the guides can fix this
2. the converter does not handle the extra `tags=...` after  `hide_tags`
  - e.g. `[source, Java, linenums, role='code_column hide_tags=copyright,Add tags=addToInvList']`

**Comment by gkwan-ibm** [comment]
for the opentracing guide, the `hideTags[]` in the converter is null, so didn't hide the code correctly

![Screen Shot 2021-06-02 at 1 25 02 PM](https://user-images.githubusercontent.com/29576299/120525341-091fd280-c3a6-11eb-8ad9-27bf6a7b87ba.png)

**Comment by gkwan-ibm** [comment]
The  opentracing guide was fixed, but need to fix the  opentracing-jaeger guide

**Comment by jakub-pomykala** [comment]
@gkwan-ibm can we close this issue now?

**Comment by jakub-pomykala** [comment]
Or replace the tags with enhancement?
