### ISSUE TITLE
No "Getting Started" section when running on guide-contract-testing

### ISSUE THREAD

**Issue by AustinSeto** [OpenLiberty/cloud-hosted-guide-converter#146]
I ran the cloud hosted guide converter on `guide-contract-testing` three times. See the following PRs generated:

- https://github.com/OpenLiberty/cloud-hosted-guides/pull/999
- https://github.com/OpenLiberty/cloud-hosted-guides/pull/1000
- https://github.com/OpenLiberty/cloud-hosted-guides/pull/1001

In all PRs, the cloud hosted guide converter failed to create a "Getting Started" section in which the user would clone the guide. Not sure what the cause of this is.

**Comment by AustinSeto** [comment]
Only occurs when the clone command and by extension - the Getting Started section - is manually included and not included using an `include` command using the file in `guides-common`.

**Comment by gkwan-ibm** [comment]
close
- there is getting started section at https://raw.githubusercontent.com/OpenLiberty/cloud-hosted-guides/staging/instructions/cloud-hosted-guide-contract-testing/instructions.md
- because no guided-project/course, cannot verify it by SN lab
- reopen if the issue occurs when course is ready
