### ISSUE TITLE
Should hide the tag and end comment in yaml file

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/cloud-hosted-guide-converter#147]
In the step  of the kube intro guide, the yaml file show all `# tag::..` and `# end::...` comments. It is better to hide them

![Screen Shot 2021-06-16 at 11 36 11 AM](https://user-images.githubusercontent.com/29576299/122249718-14d7c280-ce97-11eb-9ffd-5ffae9146c89.png)

**Comment by jakub-pomykala** [comment]
I think this issue can be closed @gkwan-ibm
