### ISSUE TITLE
Need instruction how to clone a guide repo

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/cloud-hosted-guide-converter#15]
Need to insert some instruction how to start. 
Readers don’t know where to run the `git clone ...` at step 2

e.g. Run menu `[Terminal]  > [New Terminal]`. At the terminal console run the following commands:

**Comment by jakub-pomykala** [comment]
https://github.com/OpenLiberty/quick-labs/pull/177/files PR for Quick-labs repo ( This is now added to the Guides)
