### ISSUE TITLE
Handle multiple conversions gracefully

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/cloud-hosted-guide-converter#16]
1. change a guide and merge a PR
2. the converter create a PR on the quick-labs repo, but not merge
3. another change for the same guide at step 1, and merge the PR
4. the converter should override the PR at step 2 correctly

The above should be applied to the staging and master

**Comment by jakub-pomykala** [comment]
https://github.com/OpenLiberty/quick-labs/pull/156
