### ISSUE TITLE
The Replace/Create verb should not start  by a uppercase character

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/cloud-hosted-guide-converter#160]
e.g. the converter converts
```
To use externalized configuration in the `inventory` service,
[role="code_command hotspot", subs="quotes"]
----
#Replace the `InventoryResource` class.#
`src/main/java/io/openliberty/guides/inventory/InventoryResource.java`
----
```
to
> To use externalized configuration in the inventory service, Replace the InventoryResource class.
>> From the menu of the IDE, select File > Open > guide-microprofile-config/start/src/main/java/io/openliberty/guides/inventory/InventoryResource.java

The verb **Replace** should be **replace** if the previous word is ended by a comma

**Comment by ryan-storey** [comment]
@gkwan-ibm PR ready for review [here](https://github.com/OpenLiberty/cloud-hosted-guides/pull/1092/files)
