### ISSUE TITLE
Should make the File Open/New command clear

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/cloud-hosted-guide-converter#19]
Now is showing
`[File -> Open]guide-getting-started/start/src/main/liberty/config/server.xml`

Suggest to be in two lines and have `...` after Open to match what I see for VS code
```
[File -> Open...]
guide-getting-started/start/src/main/liberty/config/server.xml
```
or
```
[File] > [Open...]
guide-getting-started/start/src/main/liberty/config/server.xml
```

![Screen Shot 2020-12-14 at 11 44 21 AM](https://user-images.githubusercontent.com/29576299/102109138-bb1c1000-3e01-11eb-8b1b-38ed7f496c6a.png)

**Comment by jakub-pomykala** [comment]
@gkwan-ibm In regards to this issue, I have re-opened however I am having difficulties rendering it the way you are requesting I have changed it to render as bellow:
```
[File] > [Open...]

guide-getting-started/start/src/main/liberty/config/server.xml
```
