### ISSUE TITLE
Step 6 and 7 of the cloud-hosted-guide-getting-started

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/cloud-hosted-guide-converter#20]
### Step 6

`[File -> Open]guide-getting-started/start/src/main/java/io/openliberty/sample/system/SystemReadinessCheck.java` 
and
`[File -> Open]guide-getting-started/start/src/main/java/io/openliberty/sample/system/SystemLivenessCheck.java`

should be
```
[File -> New File]
guide-getting-started/start/src/main/java/io/openliberty/sample/system/SystemReadinessCheck.java
```
and
```
[File -> New File]
guide-getting-started/start/src/main/java/io/openliberty/sample/system/SystemLivenessCheck.java
```

### Step 7
`[File -> Open]guide-getting-started/start/src/main/liberty/config/server.xml`
to
```
[File -> Open...]
guide-getting-started/start/src/main/liberty/config/server.xml
```

**Comment by jakub-pomykala** [comment]
#19
