### ISSUE TITLE
Show the cloud-hosted content

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/cloud-hosted-guide-converter#21]
Pending on https://github.com/OpenLiberty/guides-common/issues/562, the guide content will provide 2 sets. The converter should show the cloud-hosted content.

e.g. 
- show the cloud-hosted content provided by the guide instead of converting the url link to `curl <url>`
- a better way to resolve https://github.com/OpenLiberty/cloud-hosted-guide-converter/issues/15

**Comment by jamiecoleman92** [comment]
@gkwan-ibm The SN environment does have the ability to use a browser. We have always used curl due to a browser not providing anything extra and requiring an extra step but we could change to use the proxy function SN provide?

**Comment by gkwan-ibm** [comment]
> show the cloud-hosted content provided by the guide instead of converting the url link to curl <url>

It will be customized by using `ifdef::cloud-hosted[]`
