### ISSUE TITLE
step 2 of cloud-hosted-guide-cdi-intro

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/cloud-hosted-guide-converter#29]
the command `curl http://localhost:9080/inventory/systems` has no copy icon and having `{: codeblock} `

![Screen Shot 2020-12-15 at 10 35 24 AM](https://user-images.githubusercontent.com/29576299/102236243-44dee280-3ec1-11eb-9e83-5cba42da3ddb.png)

**Comment by gkwan-ibm** [comment]
it is the master. The staging only have 2 steps.

**Comment by jakub-pomykala** [comment]
In regards to [staging](https://labs.cognitiveclass.ai/tools/theiadocker/lab/tree?md_instructions_url=https://cf-course-data-staging.s3.us-east.cloud-object-storage.appdomain.cloud/cloud-hosted-guide-cdi-intro/instructions.md): I just re run the action and it was fine. Will close issue, please re-open if this happens again.

**Comment by jakub-pomykala** [comment]
In regards to master: I don't think there is any point changing this now as we will be changing it over to the OL SN site by the end of the week.
