### ISSUE TITLE
Adding extra functionality for ISTIO guides conversion

### ISSUE THREAD

**Issue by jakub-pomykala** [OpenLiberty/cloud-hosted-guide-converter#3]
If SN ever supports ISTIO the guide converter will need to have added functionality to remove the beginning of the bellow text. Also will have to transform the first one into a command with a copy button
![Screenshot 2020-12-01 at 13 26 02](https://user-images.githubusercontent.com/56261244/100746559-c3735480-33d8-11eb-8fad-6a653284ae1c.png)

**Comment by jamiecoleman92** [comment]
After a conversation with the SN team they have said they will not support ISTIO on their environment.
