### ISSUE TITLE
Improve Summary step

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/cloud-hosted-guide-converter#34]
- Order the "Nice work!" section first i.e. summarize what the users have learnt first

- Improve and/or clarify the relevance and why for "Clean up your environment"
  -  Why do we need to clean up?  Can the steps be automated?
  - Logout: Do we need to log out if users want to try more guides?

- Link back to https://openliberty.io/guides and/or relevant guides

@gkwan-ibm @jamiecoleman92

**Comment by yeekangc** [comment]
Related to #5.

**Comment by gkwan-ibm** [comment]
Need to ask users to stop all running process, i.e. liberty:dev, liberty:run, docker. If they not log out and try another guide, the running process may affect or screw up the application.

**Comment by jakub-pomykala** [comment]
This has been changed to the way you have recommened @yeekangc, however I think by keeping it the way it was originally it would mean that a user finishes all the steps before they see the "nice work" section. I feel like some users up on seeing this section might just leave the guide. This means that if they go to a next guide straight away their environment would have not restarted. Also I just wanted to add that if a user finishes a guide and just closes it down with out starting another one the environment will reset itself after not being used for a certain period of time.

**Comment by yeekangc** [comment]
Thank you, @jakub-pomykala.

Right, the environment will reset itself after a period of inactivity.  Then, if the user exits by accident and come back in, or if the user attempts another guide right after, that won't be the case.

The clean-up steps should be made optional if not automated as much as possible.  Users shouldn't need to worry about these.

**Comment by yeekangc** [comment]
Please let me know where I can review the changes too.

**Comment by yeekangc** [comment]
Looks like the PR is https://github.com/OpenLiberty/cloud-hosted-guide-converter/pull/36.

**Comment by yeekangc** [comment]
I will suggest we ask the users to stay logged in if they want to try out more guides.  Otherwise, they can logout.

The changes made in #36 seems fine.  I expect we will need to make further/continual improvements to optimize the experience.

**Comment by jakub-pomykala** [comment]
The changes are live in all the 7 guides' staging that we are aiming to kick off first.

**Comment by jakub-pomykala** [comment]
You can view an example in this link: https://labs.cognitiveclass.ai/tools/theiadocker/lab/tree?md_instructions_url=https://cf-course-data-staging.s3.us-east.cloud-object-storage.appdomain.cloud/cloud-hosted-guide-getting-started/instructions.md&lti=true

**Comment by jakub-pomykala** [comment]
This is fine for now, will leave issue open but change label from "must fix" to "enhancement"
