### ISSUE TITLE
Summary page vs Cleanup page

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/cloud-hosted-guide-converter#38]
If move the Nice Work! out from the "Summary" page, better rename it to "Clean up your environment"

![Screen Shot 2020-12-22 at 1 23 29 PM](https://user-images.githubusercontent.com/29576299/102920710-32345280-4459-11eb-9933-9a8597c984f7.png)

**Comment by gkwan-ibm** [comment]
@yeekangc @jamiecoleman92 @jakub-pomykala

**Comment by gkwan-ibm** [comment]
I mean either of the following:
### Option 1:
The 2nd last step has

> **Nice work!**
> You just used CDI services in Open Liberty to build a simple inventory application.

The last step will be

> ### Clean up
> Clean up your online environment so that it is ready to be used with the next guide!
> …

### Option 2:
The 2nd last step has NO Nice work!
The last step will be

> ### Summary
> **Nice work!**
> You just used CDI services in Open Liberty to build a simple inventory application.
>
> **Clean up your environment**
> Clean up your online environment so that it is ready to be used with the next guide!
> …

**Comment by gkwan-ibm** [comment]
Option 2 makes more sense because of #42

**Comment by jakub-pomykala** [comment]
Done
