### ISSUE TITLE
Cloud Hosted Rest Intro 

### ISSUE THREAD

**Issue by tt-le** [OpenLiberty/cloud-hosted-guide-converter#48]
On the Skills Network Labs draft website:
Note: not sure if this is where to open up an issue
#### Step 1 of 8
- Localhost link has a slash in front: 
<img width="392" alt="Screen Shot 2021-01-07 at 2 54 44 PM" src="https://user-images.githubusercontent.com/44335153/103938487-4a160280-50f8-11eb-89dc-790543bf4456.png">

#### Step 2 of 8
- We should prompt the user to open a new terminal in order to run the curl command

#### Step 5 of 8
- We shouldn't keep adoc tags in the xml config file
<img width="392" alt="Screen Shot 2021-01-07 at 2 57 13 PM" src="https://user-images.githubusercontent.com/44335153/103938676-a24d0480-50f8-11eb-9f36-74a599eb1109.png">

#### Step 7 of 8
- Has a misplaced curl command 
<img width="392" alt="Screen Shot 2021-01-07 at 2 58 04 PM" src="https://user-images.githubusercontent.com/44335153/103938757-c0b30000-50f8-11eb-9218-ac00daed1a09.png">

Otherwise, log in works and end to end application works as well.

**Comment by jakub-pomykala** [comment]
**Step 1** is because the original guide has a slash as well.
**Step 2** we should already be doing that (unless you mean another terminal: if so then we can add that to the cloud-hosted TWYB.adoc) 
**Step 5** issue should now be resolved (#45) 
**Step 7** issue should now also be resolved

**Comment by tt-le** [comment]
###Step 2 Yeah, I think it would be better to ask the user to open another terminal and ask them to run the curl command. If you follow the current structure, the 'current terminal' is held by the server, I think it might cause confusion to some users.

**Comment by jakub-pomykala** [comment]
That's a really good point! Thank you @tt-le i will look further into it on Monday.

**Comment by tt-le** [comment]
## Step 1
is it possible to remove the "\" from the the localhost link?

## Step 2
New issue here: 
<img width="442" alt="Screen Shot 2021-01-20 at 1 39 45 PM" src="https://user-images.githubusercontent.com/44335153/105219885-f8706d80-5b24-11eb-9afa-75f3e52b7efb.png">

## Step 7 
The curl command is still in the middle of the paragraph 

<img width="518" alt="Screen Shot 2021-01-20 at 1 42 10 PM" src="https://user-images.githubusercontent.com/44335153/105220142-4d13e880-5b25-11eb-9517-3b0f6f1030cf.png">

**Comment by jakub-pomykala** [comment]
Step 1 and 2 has now been solved looking into the curl commands

**Comment by tt-le** [comment]
LGTM. Closing 😃
