### ISSUE TITLE
Next guides in the Summary step

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/cloud-hosted-guide-converter#5]
Create links to the labs defined by the `:page-related-guides:` attribute in README.adoc

**Comment by jakub-pomykala** [comment]
Added this functionality which is added to the end of each guide. At this moment it links to Open Liberty site guides and also text is the same. This is something that can be easily changed. Please let me know about the position of this as well.


![Screenshot 2021-02-11 at 14 34 27](https://user-images.githubusercontent.com/56261244/107650379-569cf600-6c76-11eb-9bb3-1c85a7e5642f.png)


@gkwan-ibm @jamiecoleman92

**Comment by jakub-pomykala** [comment]
@gkwan-ibm this function is already implemented and also it includes iGuides aswell. However it should be revisited in regards to whether the link should be taking users to OL.io or somewhere else

**Comment by jakub-pomykala** [comment]
Waiting on confirmation in regards to where we will be pointing guides in this section too.

**Comment by gkwan-ibm** [comment]
close
- the links point to the static guides
- will reconsider when all guides can converted to cloud hosted
