### ISSUE TITLE
Feedback for Getting Started Guide - Mac/Firefox

### ISSUE THREAD

**Issue by griffinhadfield** [OpenLiberty/cloud-hosted-guide-converter#52]
Functionally, everything works well in the guide. I have a couple pieces of feedback regarding the content:

- I think that the way the user is instructed to run the curl commands could be worded better. For example, the first time the user is asked to run the command, it is phrased as such:

```
To access the system microservice, see the 

`curl http://localhost:9080/system/properties`

URL, and you see a list of the various system properties of your JVM: ...
```

Im not sure it makes sense to say "see the" followed by a command. Consider replacing it with something like:

```
Open a new tab of your command-line session and run the following command to access the system microservice:

`curl http://localhost:9080/system/properties`

You should see a list of the various system properties of your JVM: ...
```
I think the instructions preceding the curl commands should be reworded throughout the guide if possible.

- In step 8/10, the section still contains the instructions to make sure Docker is installed and to start the daemon. I don't think this applies for the cloud hosted labs because it's already set up.

**Comment by griffinhadfield** [comment]
Also, on step 5/10 the `<logging>` tag is still included in the `server.xml` file. This tag isn't supposed to be included until step 7/10. In the regular guide, this `<logging>` tag is omitted from the first version of the file that is displayed by using the `hide_tags=logging` when the file is included. I guess that is not longer working with this new setup.

**Comment by griffinhadfield** [comment]
In step 8/10, the guide indicates that the response from `docker ps` should be:
```
CONTAINER ID    IMAGE                         CREATED          STATUS           NAMES
4294a6bdf41b    openliberty-getting-started   9 seconds ago    Up 11 seconds    gettingstarted-app
```

However the response I am receiving is:
```
CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS              PORTS                              NAMES
1f8f400d5d89        openliberty-getting-started:1.0-SNAPSHOT   "/opt/ol/helpers/run…"   8 seconds ago       Up 5 seconds        0.0.0.0:9080->9080/tcp, 9443/tcp   gettingstarted-app
```

**Comment by jakub-pomykala** [comment]
Step 5 will be reopened as "enhancement" for the future.

In regards to step 8 this is pulled straight from guide-getting-started, therefore I can't change this. What we could do is in the future set up a file and when this is detected in a Guide it will replace it. I will close this issues

**Comment by griffinhadfield** [comment]
@jakub-pomykala Is there a new places I should open an issue so that these things can be fixed in the future?

**Comment by jakub-pomykala** [comment]
Re-opening issue as a enhancement instead of must fix. Need to remove docker include. Also try looking at switching the docker output to the right one. Thank you @griffinhadfield

**Comment by jakub-pomykala** [comment]
In regards to the docker output message: after discussing with @gkwan-ibm and @jamiecoleman92 it came out that the output message in the original guide is outdated. I am closing this issue and I have opened a new one in the guide-getting-strted repo ([here](https://github.com/OpenLiberty/guide-getting-started/issues/224))
