### ISSUE TITLE
Feedback for guide-cdi-intro

### ISSUE THREAD

**Issue by AustinSeto** [OpenLiberty/cloud-hosted-guide-converter#53]
Tested using login with LinkedIn

Tested on Windows 10 on Firefox

***

# General

- [x] When the user is asked to create/modify certain files, the highlighting appears to miss `package`

# Step 1

- [x] The link to the `guide-rest-intro` links to the guide on openliberty.io, unsure if intended or if these links are intended to link to the guides on the cloud hosted platform

# Step 2

- [ ] When it asks you to point the browser to a URL, this isn't applicable for the cloud hosted guides
  - Perhaps mentions of localhost:9080 can be replaced with something like `austinseto-9080.theiadocker-8.proxy.cognitiveclas.ai` (the URL I had) or similar?
  - `curl` command cannot be used before opening another terminal as the application is running the first terminal

# Step 4

- [x] The URLs displayed are incorrect (besides previously noted issue regarding localhost)
  - Only 1 URL is listed (guide on openliberty.io lists 2 URLs)
  - Random dash appears instead, I think URL got cut off or similar, excerpt copy pasted below

Excerpt:

You can find the **inventory** and **system** services at the following URLs:

- 

```
curl http://localhost:9080/inventory/systems
```

**Comment by tt-le** [comment]
Follow up to fixes above.

### Step 4
Suggestion to put the links as a list:
- link1
- link2
or as list of commands:
- `curl link1`
- `curl link2`
<img width="455" alt="Screen Shot 2021-01-14 at 3 17 40 PM" src="https://user-images.githubusercontent.com/44335153/104644339-a68a9c00-567b-11eb-828d-425ef3287fc6.png">

Everything else seems fine except for the 'point to browser' stuff which was already mentioned above. 
End to end works; no issues. Tested linkedin login, on windows 10 with chrome browser.

**Comment by jakub-pomykala** [comment]
This should now be resolved
