### ISSUE TITLE
Feedback for cloud hosted microprofile config guide

### ISSUE THREAD

**Issue by tt-le** [OpenLiberty/cloud-hosted-guide-converter#54]
#### Step 2 of 10 
Should ask for users to open a new terminal before prompting the `curl` commands
<img width="509" alt="Screen Shot 2021-01-11 at 12 57 55 PM" src="https://user-images.githubusercontent.com/44335153/104219828-a20c7c00-540c-11eb-9aed-829c148f58a7.png">
#### Step of 10
Issue with parsing the property name:
<img width="501" alt="Screen Shot 2021-01-11 at 1 08 04 PM" src="https://user-images.githubusercontent.com/44335153/104220815-0c71ec00-540e-11eb-9477-9cc5b9ed248f.png">
<img width="501" alt="Screen Shot 2021-01-11 at 1 10 29 PM" src="https://user-images.githubusercontent.com/44335153/104221058-64105780-540e-11eb-99c7-2e76617b7c82.png">

#### Step 5 of 10
Suggestion to change `Note that three default config sources mentioned **above** are static and fixed on application...` to 
`Note that three default config sources mentioned **in the previous step** are static and fixed on application...` or something similar
<img width="501" alt="Screen Shot 2021-01-11 at 1 15 27 PM" src="https://user-images.githubusercontent.com/44335153/104221595-1516f200-540f-11eb-9c64-5c6f0099961b.png">
Property names not parsed correctly:
<img width="522" alt="Screen Shot 2021-01-11 at 2 17 04 PM" src="https://user-images.githubusercontent.com/44335153/104227616-b1dd8d80-5417-11eb-8fcb-f406f4cfc109.png">

#### Step 6 of 10

<img width="522" alt="Screen Shot 2021-01-11 at 2 20 27 PM" src="https://user-images.githubusercontent.com/44335153/104227958-29132180-5418-11eb-886f-288e3d4e4ec7.png">

#### Step 8 of 10

<img width="522" alt="Screen Shot 2021-01-11 at 4 14 02 PM" src="https://user-images.githubusercontent.com/44335153/104239143-0852c800-5428-11eb-96ca-97f7984cca9e.png">

#### Step 9 of 10

<img width="522" alt="Screen Shot 2021-01-11 at 4 15 40 PM" src="https://user-images.githubusercontent.com/44335153/104239274-4223ce80-5428-11eb-9390-dda98f38a5c8.png">

Login and log out was working properly. Integration test passed. End to end works as expected too.

**Comment by jakub-pomykala** [comment]
This should now be resolved. The italic problem has a temp fix in place (waiting for Skills Network team to give a permanent fix). In regards to the suggestion, there is not much I can do with out hard coding the GuideConverter for the specific case which is something we are trying to avoid as much as possible
