### ISSUE TITLE
Can't copy and paste into editor on Linux

### ISSUE THREAD

**Issue by griffinhadfield** [OpenLiberty/cloud-hosted-guide-converter#57]
When trying to copy the new code from the left pane into the editor on the right, the error message pops up:
<img width="822" alt="Screenshot 2021-01-12 at 2 17 03 PM" src="https://user-images.githubusercontent.com/38739044/104363375-16b1ea00-54e3-11eb-8172-75e11d556727.png">

I am able to successfully copy and paste into the terminal, the issue is only with the editor. Also, if I copy using the browser's copy and paste, it works fine.

This was tested on a Linux VM using Firefox. This could be an issue unique to testing on a VM, but this is my only way to test it.

**Comment by jakub-pomykala** [comment]
@austin0 @jamiecoleman92

**Comment by jakub-pomykala** [comment]
@griffinhadfield could you please re open this issue in the quick-labs repo as this is irrelevant to the guideConverter. Thanks in advance
