### ISSUE TITLE
Feedback for Getting Started Guide - Mac/Chrome

### ISSUE THREAD

**Issue by meswan** [OpenLiberty/cloud-hosted-guide-converter#60]
*Step 9*
![image](https://user-images.githubusercontent.com/31047835/104494365-5db3e400-55a4-11eb-9125-f69fab19652f.png)

Consider having "Navigate to the target directory" on its own line so that its clearer or add a `cd` command to the target directory

*Overall*
The text surrounding the curl statements need to be revised. The guide itself worked as expected.

**Comment by jakub-pomykala** [comment]
In regards to step 9 I can not change the wording. As it comes directly from the actual guide. 

Text around curl commands should be changed now. :)
