### ISSUE TITLE
Change command line output

### ISSUE THREAD

**Issue by jakub-pomykala** [OpenLiberty/cloud-hosted-guide-converter#65]
Some commands will be giving different outputs for users when using the build in environment. We can add this to the guide Converter by running commands and finding the different outputs and then adding these outputs to the `cloud-hosted` file of Guides-common. Then switch the outcomes when the converter finds an output that should be different

**Comment by jamiecoleman92** [comment]
This issue is resolved by keeping all pre-reqs upto date on the SN environment and our guides.
