### ISSUE TITLE
Switch localhost to username

### ISSUE THREAD

**Issue by jakub-pomykala** [OpenLiberty/cloud-hosted-guide-converter#66]
When it asks user to point the browser to a URL, this isn't applicable for the cloud hosted guides
Perhaps mentions of localhost:9080 can be replaced with something like `jakubpomykala-9080.theiadocker-8.proxy.cognitiveclas.ai` or similar?

**Comment by jamiecoleman92** [comment]
This will not be possible/easy to achieve and will bring little benifit to the user.
