### ISSUE TITLE
Feedback for containerize guide

### ISSUE THREAD

**Issue by tt-le** [OpenLiberty/cloud-hosted-guide-converter#84]
### Step 2
- [x] Missing the getting started part (open terminal + git clone etc)
### Step 4 

<img width="564" alt="Screen Shot 2021-01-26 at 12 00 13 PM" src="https://user-images.githubusercontent.com/44335153/105877493-10853880-5fce-11eb-8434-ad53d220b7aa.png">

- [ ] Link doesn't match the guide `http://localhost:9081/inventory/systems/pass:c[[system-ip-address]]` -> `http://localhost:9081/inventory/systems/[system-ip-address]`
- [ ] There should be a curl command associated to that link
- [x] problem here as well `http://localhost:9081/inventory/systems[http://localhost:9081/inventory/systems^] `

### Step 5
<img width="564" alt="Screen Shot 2021-01-26 at 12 03 45 PM" src="https://user-images.githubusercontent.com/44335153/105877970-8c7f8080-5fce-11eb-9d24-c578aaaf1e65.png">

- [ ] same thing here, `http://localhost:9081/inventory/systems/pass:c[[system-ip-address]]` -> `http://localhost:9081/inventory/systems/[system-ip-address]`
- [ ] and we should also add a curl associated with that link 

### Step 6
<img width="564" alt="Screen Shot 2021-01-26 at 12 09 25 PM" src="https://user-images.githubusercontent.com/44335153/105878734-57276280-5fcf-11eb-9e36-14ac5d2ebb00.png">
<img width="564" alt="Screen Shot 2021-01-26 at 12 09 38 PM" src="https://user-images.githubusercontent.com/44335153/105878754-5ee70700-5fcf-11eb-868d-e141df3dce8e.png">

- [x] can't go to step 7?

### Step 7 

End to end works!

**Comment by jakub-pomykala** [comment]
The reason why http://localhost:9081/inventory/systems/[system-ip-address] does not have a curl command is because it is a key phrase/word. and it is in a bold text. @gkwan-ibm do we want it to have a curl command?

**Comment by gkwan-ibm** [comment]
for step 5, yes and no 
- no, the syntax `\http:` for the convertor is no need to add a curl command
- yes, the content require to have a curl command by need users to replace the url

Need to be address by #74

**Comment by jakub-pomykala** [comment]
Okay, adding enhancement tag to this post and leaving till next the next batch of guides.

**Comment by gkwan-ibm** [comment]
step 4 and 5 issues should be addressed by #95

**Comment by gkwan-ibm** [comment]
close
- all feedback should be addressed 
- more feedback will be created by other issue
