### ISSUE TITLE
Feedback for MP config

### ISSUE THREAD

**Issue by tt-le** [OpenLiberty/cloud-hosted-guide-converter#85]
#### Step 5
- [x] The code block is commented out
<img width="520" alt="Screen Shot 2021-01-27 at 1 12 05 PM" src="https://user-images.githubusercontent.com/44335153/106034735-421b0400-60a1-11eb-8342-6dc55346820d.png">

**Comment by jakub-pomykala** [comment]
The codeblock has now been fixed: 

![Uploading Screenshot 2021-01-28 at 08.42.21.png…]()
