### ISSUE TITLE
Support different sets of instruction

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/cloud-hosted-guide-converter#95]
The guide provides 2 sets of instruction. One is for the static guide, and other is particular for the cloud-hosted guide. Like following:
![Screen Shot 2021-02-08 at 5 41 33 PM](https://user-images.githubusercontent.com/29576299/107291449-3252d680-6a36-11eb-9648-b784500ef3c7.png)

Converter can do 
- skip the following content (line 255~277)

```
ifndef::cloud-hosted[] 
...
endif::[]
```
- skip the line 280 `ifdef::cloud-hosted[]`
- use the content between `ifdef::cloud-hosted[]` and `endif::[]` (line 281~286) without conversion because it is in md format
- skip the line 287 `endif::[]`

**Comment by jakub-pomykala** [comment]
This is great! Thank you @gkwan-ibm

**Comment by jakub-pomykala** [comment]
Reopening until functionality can be verified.

**Comment by jamiecoleman92** [comment]
@gkwan-ibm is this a mustfix issue?

**Comment by jakub-pomykala** [comment]
This has now been tested using @gkwan-ibm [branch in the guide-conteinerize repo ](https://github.com/OpenLiberty/guide-containerize/tree/gkwan-ibm-cloud-hosted). This fix is fully functional. After merge into QA and Master/Main the fix will go live in the cloud-hosted-guides.
